apiVersion: batch/v1
kind: CronJob
metadata:
  name: crawler
  namespace: tsmc-nycu-lab-13
spec:
  schedule: "59 23 * * *"
  suspend: true
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: crawler
            sidecar.istio.io/inject: "false"
        spec:
          containers:
          - image: quay.io/tsmc-nycu-lab-13/crawler
            name: crawler
            envFrom:
              - secretRef:
                  name: crawler-env
            command:
              - "python"
              - "crawler.py"
            resources:
              requests:
                memory: "128M"
                cpu: "500m"
          restartPolicy: Never
