name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

env:
  APP_URL: 127.0.0.1
  APP_PORT: 8000
  APP_DEBUG: True
  DB_CONNECTION: mariadb
  DB_HOST: 127.0.0.1
  DB_PORT: 3306
  DB_DATABASE: fastapi
  DB_TABLE: articles
  DB_USERNAME: root
  DB_PASSWORD: ${{ secrets.RootPassword }}

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: getong/mariadb-action@v1.1
        with:
          mariadb version: '10.4.10'
          mysql database: 'fastapi_test'
          mysql root password: ${{ secrets.RootPassword }}

      - run: |
          sudo apt-get update
          sudo apt-get -yy install gcc libmariadb3 libmariadb-dev

      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      # - name: Run image
      #   uses: abatilo/actions-poetry@v2.0.0
      #   with:
      #     poetry-version: 1.1.13
      - run: pip install -r requirements.txt
      - run: pip install pylint coverage
      - run: coverage run -m unittest discover
      - run: coverage report
      - run: coverage html
      - run: coverage xml
      - uses: actions/upload-artifact@v2
        with:
          name: code-coverage
          path: htmlcov

  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
